language: java

jdk:
  - oraclejdk8

sudo: false

branches:
  only:
    - master

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - FILES_DIR: "./files"
    - ROOT_USER: "test"
    - ROOT_PASSWORD: "password"