version: '2'
services:
  database-dev:
    image: mongo
    container_name: database-dev
    # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # environment:
    #   - MYSQL_DATABASE=data-dev
    #   - MYSQL_USER=data-dev
    #   - MYSQL_PASSWORD=password
    #   - MYSQL_ROOT_PASSWORD=password
    volumes:
      - dev_db:/var/lib/mysql
    ports:
      - "3306:3306"
  api-dev:
    image: nector12/sttdb-server-test
    container_name: api-dev
    depends_on:
      - database-dev
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=sttdb.dev.rhizomik.net
      - LETSENCRYPT_HOST=sttdb.dev.rhizomik.net
      - LETSENCRYPT_EMAIL=contact@email.example
      - SPRING_PROFILES_ACTIVE=production
      - DATABASE_URL=jdbc:mongo://dev.rhizomik.net:3306/data-dev
      - DATABASE_USERNAME=data-dev
      - DATABASE_PASSWORD=password
      - JAVA_OPTS=-Xmx256m -Xms128m
    network_mode: "bridge"
volumes:
  dev_db:
    external: true
